name: New Branch

on:
  create:
    branches:
      - '**'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: execute bash script
        run: |
            bash device_status_report.sh ${{ github.ref_name }} ${{ secrets.API_User }} ${{ secrets.API_Pass }} ${{ secrets.JIRA_USERNAME }} ${{ secrets.JIRA_PASSWORD }}
