name: Check for updated macOS versions
on:
  schedule:
    - cron: "0 */4 * * *" # Every 4 hours at the top of the hour
on: workflow_dispatch

jobs:
  run-script:
    runs-on: macos-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Get new os versions
        run: |
          bash nudge-updater.sh
