name: Update Versions

on: workflow_dispatch

jobs:
  run-script:
    runs-on: macos

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Get new os versions
        run: |
          bash os-version-cronjob.sh ${{ secrets.TOKEN }}
